/* Generated by cbindgen — do not edit manually */

#ifndef INSTANTLINK_FFI_H
#define INSTANTLINK_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the FFI layer (logging + runtime). Safe to call multiple times.
 */
void instantlink_init(void);

/**
 * Scan for nearby Instax printers.
 *
 * Writes a JSON array of printer name strings into `out_json`.
 * Returns the number of bytes written (excluding NUL), or a negative error code.
 *
 * # Safety
 *
 * `out_json` must point to a buffer of at least `out_len` bytes.
 */
int32_t instantlink_scan(int32_t duration_secs, char *out_json, int32_t out_len);

/**
 * Connect to the first available Instax printer.
 * Returns 0 on success, negative error code on failure.
 */
int32_t instantlink_connect(void);

/**
 * Connect to a specific printer by name with configurable scan duration.
 *
 * `duration_secs` sets the BLE scan duration; pass 0 for the default.
 *
 * # Safety
 *
 * `name` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t instantlink_connect_named(const char *name, int32_t duration_secs);

/**
 * Disconnect from the current printer.
 */
int32_t instantlink_disconnect(void);

/**
 * Get battery level (0-100). Returns negative error code on failure.
 */
int32_t instantlink_battery(void);

/**
 * Get remaining film count. Returns negative error code on failure.
 */
int32_t instantlink_film_remaining(void);

/**
 * Get film remaining and charging state in one call.
 *
 * On success, writes film count to `*out_film` and charging flag (0 or 1)
 * to `*out_charging`, and returns 0.
 *
 * # Safety
 *
 * `out_film` and `out_charging` must be valid, non-null pointers.
 */
int32_t instantlink_film_and_charging(int32_t *out_film, int32_t *out_charging);

/**
 * Get total print count. Returns negative error code on failure.
 */
int32_t instantlink_print_count(void);

/**
 * Get all status fields in one call (battery, film, charging, print count).
 *
 * This performs a single mutex lock and one `block_on` call, making it
 * significantly faster than calling the individual getters separately.
 *
 * # Safety
 *
 * All output pointers must be valid and non-null.
 */
int32_t instantlink_status(int32_t *out_battery,
                           int32_t *out_film,
                           int32_t *out_charging,
                           int32_t *out_print_count);

/**
 * Get the connected device's BLE name.
 *
 * Returns number of bytes written (excluding NUL), or negative error.
 *
 * # Safety
 *
 * `out` must point to a buffer of at least `out_len` bytes.
 */
int32_t instantlink_device_name(char *out, int32_t out_len);

/**
 * Get the connected device's model string (e.g. "Instax Mini Link").
 *
 * Returns number of bytes written (excluding NUL), or negative error.
 *
 * # Safety
 *
 * `out` must point to a buffer of at least `out_len` bytes.
 */
int32_t instantlink_device_model(char *out, int32_t out_len);

/**
 * Print an image file. Returns 0 on success, negative error code on failure.
 *
 * - `quality`: JPEG quality 1-100
 * - `fit_mode`: 0 = crop, 1 = contain, 2 = stretch
 * - `print_option`: 0 = default/Rich, 1 = Natural (passed to device)
 *
 * # Safety
 *
 * `path` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t instantlink_print(const char *path,
                          uint8_t quality,
                          uint8_t fit_mode,
                          uint8_t print_option);

/**
 * Print an image file with progress callback. Returns 0 on success.
 *
 * The callback receives (chunks_sent, total_chunks) after each chunk is ACK'd.
 *
 * # Safety
 *
 * `path` must be a valid, non-null, null-terminated UTF-8 C string.
 * `progress_cb` may be null (no progress reporting).
 */
int32_t instantlink_print_with_progress(const char *path,
                                        uint8_t quality,
                                        uint8_t fit_mode,
                                        uint8_t print_option,
                                        void (*progress_cb)(uint32_t, uint32_t));

/**
 * Set LED color and pattern.
 */
int32_t instantlink_set_led(uint8_t r, uint8_t g, uint8_t b, uint8_t pattern);

/**
 * Turn off the LED.
 */
int32_t instantlink_led_off(void);

/**
 * Check if a printer is currently connected.
 * Returns 1 if connected, 0 if not, -3 on error.
 */
int32_t instantlink_is_connected(void);

#endif  /* INSTANTLINK_FFI_H */
