from __future__ import annotations

from instantlink_bridge.update.signing import (
    SIGNATURE_ALGORITHM,
    SIGNATURE_KIND,
    SIGNATURE_SCHEMA_VERSION,
    SIGNED_PAYLOAD,
    FirmwareManifestError,
    FirmwareManifestVerification,
    FirmwareSignatureError,
    FirmwareSigningError,
    FirmwareSigningUnavailableError,
    canonical_json_bytes,
    default_signature_path,
    key_id_for_public_key,
    load_json_object,
    load_private_key,
    public_key_bytes,
    public_key_text,
    sign_manifest,
    validate_firmware_manifest,
    verify_manifest_file,
    verify_manifest_signature,
    write_json_object,
)

__all__ = [
    "SIGNATURE_ALGORITHM",
    "SIGNATURE_KIND",
    "SIGNATURE_SCHEMA_VERSION",
    "SIGNED_PAYLOAD",
    "FirmwareManifestError",
    "FirmwareManifestVerification",
    "FirmwareSignatureError",
    "FirmwareSigningError",
    "FirmwareSigningUnavailableError",
    "canonical_json_bytes",
    "default_signature_path",
    "key_id_for_public_key",
    "load_json_object",
    "load_private_key",
    "public_key_bytes",
    "public_key_text",
    "sign_manifest",
    "validate_firmware_manifest",
    "verify_manifest_file",
    "verify_manifest_signature",
    "write_json_object",
]
