"""UI state models."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from PIL import Image

from instantlink_bridge.ble.models import PrinterModel
from instantlink_bridge.imaging.postprocess import AdjustmentProfile


class UiMode(StrEnum):
    """Top-level LCD modes."""

    BOOTING = "booting"
    SETTINGS = "settings"
    ADJUSTMENT_EDIT = "adjustment_edit"
    NEEDS_PAIRING = "needs_pairing"
    PAIRING = "pairing"
    PRINTER_SEARCHING = "printer_searching"
    PRINTER_OFFLINE = "printer_offline"
    VALIDATION = "validation"
    READY = "ready"
    NO_FILM = "no_film"
    IMAGE_RECEIVED = "image_received"
    AWAITING_CONFIRM = "awaiting_confirm"
    PRINTING = "printing"
    PRINT_COMPLETE = "print_complete"
    PAIR_FAILED = "pair_failed"
    ERROR = "error"
    # iOS-style yes/no dialog overlay (plan 040). Replaces the per-flow
    # two-press confirms; the controller stamps the action_key into the
    # snapshot and dispatches on confirm.
    CONFIRMATION_DIALOG = "confirmation_dialog"


class UiAction(StrEnum):
    """Actions generated by joystick and KEY1-KEY3."""

    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"
    SELECT = "select"
    BACK = "back"
    HELP = "help"
    PAIR = "pair"


@dataclass(frozen=True, slots=True)
class PairedPrinter:
    """A selected Bluetooth printer."""

    address: str
    name: str
    model: PrinterModel | None = None


@dataclass(frozen=True, slots=True)
class SettingsRow:
    """A single LCD settings menu row.

    ``is_header`` marks visual section dividers (e.g. "Diagnostics",
    "Advanced", "Personalisation"). The render layer styles header rows
    with a smaller font, secondary tint, no row hairline, and reduced
    height so they read as labels rather than greyed-out selectable rows.

    ``i18n_value_prefix`` is a translatable prefix that the render layer
    composes with ``value`` at draw time (e.g. ``"On"`` + ``" · \"Hello\""``).
    Useful for composite values where only the leading word needs i18n.
    """

    label: str
    value: str
    hint: str = ""
    help: str = ""
    is_header: bool = False
    i18n_value_prefix: str = ""


@dataclass(frozen=True, slots=True)
class UiSnapshot:
    """Immutable LCD render input."""

    mode: UiMode
    ftp_host: str
    ftp_receive_mode: str = "auto"
    wifi_host: str | None = None
    hotspot_host: str | None = None
    hotspot_ssid: str | None = None
    hotspot_ftp_host: str = "192.168.8.1"
    preferred_wifi_host: str | None = None
    usb_connected: bool = False
    camera_receive_ready: bool = False
    camera_connected: bool = False
    camera_status_message: str | None = None
    camera_transport_message: str | None = None
    paired_printer: PairedPrinter | None = None
    selected_index: int = 0
    last_image_name: str | None = None
    film_remaining: int | None = None
    film_capacity: int = 10
    printer_battery: int | None = None
    printer_is_charging: bool | None = None
    printer_battery_minutes_remaining: int | None = None
    printer_model: PrinterModel | None = None
    printer_status_message: str | None = None
    printer_status_fresh: bool = False
    bridge_battery_percent: int | None = None
    bridge_power_model: str | None = None
    bridge_power_status: str | None = None
    bridge_power_alert: str = "unknown"
    bridge_external_power: bool | None = None
    idle_stage: str = "active"
    message: str | None = None
    print_title: str | None = None
    print_detail: str | None = None
    print_progress_percent: int | None = None
    allow_print_without_film: bool = False
    preview_image: Image.Image | None = None
    preview_tool: str = "zoom"
    preview_zoom: float = 1.0
    preview_rotation_degrees: int = 0
    preview_offset_x: float = 0.0
    preview_offset_y: float = 0.0
    settings_title: str = "Settings"
    settings_rows: tuple[SettingsRow, ...] = ()
    settings_message: str | None = None
    font_size: str = "medium"
    language: str = "en"
    appearance: str = "light"
    image_queue_depth: int = 0
    adjustments_profile: AdjustmentProfile | None = None
    # Focused adjustment-edit mode state (plan 036 phase 4).
    # adjustment_edit_key: which axis is being edited (None outside ADJUSTMENT_EDIT).
    # Use str to avoid circular import with settings.SettingKey.
    adjustment_edit_key: str | None = None
    adjustment_edit_value: int = 0
    adjustment_edit_original: int = 0
    # iOS-style confirmation-dialog overlay (plan 040). Populated only while
    # ``mode is UiMode.CONFIRMATION_DIALOG``; the controller registers an
    # ``action_key`` when opening the dialog and dispatches the matching
    # ``_execute_*`` method when the user activates the Confirm button. Keeping
    # the state inside the frozen snapshot (instead of a callable on the
    # controller) preserves Equatable semantics and renderer purity.
    confirmation_title: str | None = None
    confirmation_message: str | None = None
    confirmation_confirm_label: str = "OK"
    confirmation_destructive: bool = False
    confirmation_focus: str = "cancel"  # "cancel" | "confirm"
    confirmation_action_key: str | None = None
