"""UI state models."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from PIL import Image

from instantlink_bridge.ble.models import PrinterModel


class UiMode(StrEnum):
    """Top-level LCD modes."""

    BOOTING = "booting"
    SETTINGS = "settings"
    NEEDS_PAIRING = "needs_pairing"
    PAIRING = "pairing"
    PRINTER_SEARCHING = "printer_searching"
    PRINTER_OFFLINE = "printer_offline"
    VALIDATION = "validation"
    READY = "ready"
    NO_FILM = "no_film"
    IMAGE_RECEIVED = "image_received"
    AWAITING_CONFIRM = "awaiting_confirm"
    PRINTING = "printing"
    PRINT_COMPLETE = "print_complete"
    PAIR_FAILED = "pair_failed"
    ERROR = "error"


class UiAction(StrEnum):
    """Actions generated by joystick and KEY1-KEY3."""

    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"
    SELECT = "select"
    BACK = "back"
    HELP = "help"
    PAIR = "pair"


@dataclass(frozen=True, slots=True)
class PairedPrinter:
    """A selected Bluetooth printer."""

    address: str
    name: str
    model: PrinterModel | None = None


@dataclass(frozen=True, slots=True)
class SettingsRow:
    """A single LCD settings menu row."""

    label: str
    value: str
    hint: str = ""


@dataclass(frozen=True, slots=True)
class UiSnapshot:
    """Immutable LCD render input."""

    mode: UiMode
    ftp_host: str
    ftp_receive_mode: str = "auto"
    wifi_host: str | None = None
    hotspot_host: str | None = None
    hotspot_ftp_host: str = "192.168.8.1"
    preferred_wifi_host: str | None = None
    usb_connected: bool = False
    camera_receive_ready: bool = False
    camera_connected: bool = False
    camera_status_message: str | None = None
    camera_transport_message: str | None = None
    paired_printer: PairedPrinter | None = None
    selected_index: int = 0
    last_image_name: str | None = None
    film_remaining: int | None = None
    film_capacity: int = 10
    printer_battery: int | None = None
    printer_is_charging: bool | None = None
    printer_battery_minutes_remaining: int | None = None
    printer_model: PrinterModel | None = None
    printer_status_message: str | None = None
    bridge_battery_percent: int | None = None
    bridge_power_model: str | None = None
    bridge_power_status: str | None = None
    bridge_power_alert: str = "unknown"
    bridge_external_power: bool | None = None
    idle_stage: str = "active"
    message: str | None = None
    print_title: str | None = None
    print_detail: str | None = None
    print_progress_percent: int | None = None
    allow_print_without_film: bool = False
    preview_image: Image.Image | None = None
    preview_tool: str = "zoom"
    preview_zoom: float = 1.0
    preview_rotation_degrees: int = 0
    preview_offset_x: float = 0.0
    preview_offset_y: float = 0.0
    settings_title: str = "Settings"
    settings_rows: tuple[SettingsRow, ...] = ()
    settings_message: str | None = None
