/* Generated by cbindgen — do not edit manually */

#ifndef OPENINSTAX_FFI_H
#define OPENINSTAX_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the FFI layer (logging + runtime). Safe to call multiple times.
 */
void openinstax_init(void);

/**
 * Connect to the first available Instax printer.
 * Returns 0 on success, negative error code on failure.
 */
int32_t openinstax_connect(void);

/**
 * Connect to a specific printer by name.
 *
 * # Safety
 *
 * `name` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t openinstax_connect_named(const char *name);

/**
 * Disconnect from the current printer.
 */
int32_t openinstax_disconnect(void);

/**
 * Get battery level (0-100). Returns negative error code on failure.
 */
int32_t openinstax_battery(void);

/**
 * Get remaining film count. Returns negative error code on failure.
 */
int32_t openinstax_film_remaining(void);

/**
 * Print an image file. Returns 0 on success, negative error code on failure.
 *
 * # Safety
 *
 * `path` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t openinstax_print(const char *path, uint8_t quality, uint8_t fit_mode);

/**
 * Set LED color and pattern.
 */
int32_t openinstax_set_led(uint8_t r, uint8_t g, uint8_t b, uint8_t pattern);

/**
 * Turn off the LED.
 */
int32_t openinstax_led_off(void);

/**
 * Check if a printer is currently connected.
 * Returns 1 if connected, 0 if not.
 */
int32_t openinstax_is_connected(void);

#endif  /* OPENINSTAX_FFI_H */
